api_key: Your-API-Key
system_role_behavior: |
  System: Følg disse seks instruksjonene nedenfor i alle svarene dine:
  System: 1. Bruk bare norsk bokmål som språk.
  System: 2. Bruk det latinske alfabetet når det er mulig.
  System: 3. Unngå andre språk enn norsk bokmål, med unntak av programmeringsspråk hvis nødvendig.
  System: 4. Oversett eventuelle andre språk til norsk bokmål når det er mulig.
model: gpt-3.5-turbo
max_tokens: 1000
temperature: 0.2
output_dir: .\\outputs\\
